# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: Library_app-development
  pool: 5
  username: BillFogg
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Library_app-test
  pool: 5
  username: BillFogg
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Library_app-production
  pool: 5
  username: BillFogg
  password: